### ISSUE TITLE
On message receive - Uncaught Exception:  TypeError: Cannot assign to read only property 'writeQueueSize' of object '#<TCP>'

### ISSUE THREAD

**Issue by potatoronin** [madmax3365/node-red-node-discord#23]
```
TypeError: Cannot assign to read only property 'writeQueueSize' of object '#<TCP>'
    at _clone (/usr/lib/node_modules/node-red/node_modules/clone/clone.js:162:16)
    at _clone (/usr/lib/node_modules/node-red/node_modules/clone/clone.js:162:18)
nodered.service: Main process exited, code=exited, status=1/FAILURE
```

I run NodeRed as part of Raspbian install. Was able to receive message ONCE, after that any message, crashes the NodeRed.

**Comment by madmax3365** [comment]
Hey Alex. 
I think one of the fields contains `Promise`.
When you forking output node the `node-red` fails to clone the message.
If that's your case, then it will be fixed in `V3`.
I'm currently working on it and planning to release it in a few days

**Comment by madmax3365** [comment]
Possible duplication of #1
