### ISSUE TITLE
Upgrade DiscordJS to 12.x.x

### ISSUE THREAD

**Issue by MarkOSullivan94** [madmax3365/node-red-node-discord#4]
Noticed that the DiscordJS package has a `12.x.x` release and `11.6.x` release.

Given how `12.x.x` introduces a lot of breaking changes, it might be better to upgrade to `11.6.x` first which fixes a lot of bugs which was in `11.5.x`.

**Comment by MarkOSullivan94** [comment]
Moved these changes to a different branch in my fork and opened a PR to get the changes merged in from that branch: https://github.com/madmax3365/node-red-node-discord/pull/7

**Comment by madmax3365** [comment]
Yes, you're right. The repo needs to upgrade. I had no time for this, but in near feature going to publish the new version.

**Comment by Eeems** [comment]
@madmax3365 When exactly is the near future? Currently this is completely broken as the old DiscordJS package no longer seems to work with the discord API and is bringing down my node-red instance with the following error:
```
TypeError: Cannot read property 'id' of undefined
    at ClientDataManager.newChannel (/data/node_modules/discord.js/src/client/ClientDataManager.js:81:36)
    at Guild.setup (/data/node_modules/discord.js/src/structures/Guild.js:307:68)
    at GuildCreateHandler.handle (/data/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
    at WebSocketPacketManager.handle (/data/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/data/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/data/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/data/node_modules/discord.js/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/data/node_modules/discord.js/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/data/node_modules/discord.js/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/data/node_modules/discord.js/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/data/node_modules/discord.js/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/data/node_modules/discord.js/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at TLSSocket.socketOnData (/data/node_modules/discord.js/node_modules/ws/lib/websocket.js:864:35)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by Eeems** [comment]
Opened an issue to track the specific crashing I'm getting.
